### ISSUE TITLE
Feature: Don't output coverage results after generating coverage results.

### ISSUE THREAD

**Issue by lsh-0** [CleanCut/green#131]
It doesn't look like the coverage support in green picks up coverage's `.coveragerc` file for configuration. 

If all of coverage's options were supported on the command line, or if green didn't print the coverage report afterwards this wouldn't be an issue.

**Comment by CleanCut** [comment]
> if green didn't print the coverage report afterwards

Green doesn't print the coverage report afterwards unless you ask it to.  You have to specify `-r` or `--run-coverage`

What do you see happening in your environment?

**Comment by lsh-0** [comment]
When I run green without `--run-coverage`, the `.coverage` results file is *not* created. 

When I run green *with* `--run-coverage`, the `.coverage` results file *is* created, but the report is also printed. The report doesn't appear to obey the configuration in the `.coveragerc` file.

**Comment by lsh-0** [comment]
`Python 2.7.12`, `green==2.5.0` and `coverage==4.1` if it helps.

**Comment by CleanCut** [comment]
Okay, I see what you are saying.  I think there is simply some confusion regarding the

The `--run-coverage` option for green causes it to enable coverage on tests that it runs _and then green prints it the results_.  So that's actually part of the feature in green, which is why coverage isn't affected by it -- green is calling the coverage output itself.  The rest of coverage's behaviour should be affected by `.coveragerc`, since that's up to coverage's independent behavior.

We could certainly make a green output option to _not_ print coverage results, even if it were run.  That would simply be a new feature, though.

**Comment by althonos** [comment]
@CleanCut: I just realized this is a duplicate of #148 (which I forgot to check before creating a new issue). I guess you could close it 

@lsh-0: check out the version 2.6.0, it integrates the PR in which I added this feature.

**Comment by lsh-0** [comment]
looks promising, cheers @althonos

**Comment by CleanCut** [comment]
Closing duplicate of #148
