### ISSUE TITLE
Feature request: pytest integration?

### ISSUE THREAD

**Issue by chrischambers** [CleanCut/green#151]
Sorry to be "that guy", but it'd be fantastic if green could hook into pytest and use its test discovery mechanisms. Is this on the horizons? And if so, is it something you're working on or would it be something someone would have to contribute?

Thanks!

**Comment by CleanCut** [comment]
No worries.  This is the place for requests like that.  The worst that can happen is that we just let you know that the answer is "no" -- which is always a possibility because we are not trying to be all things for all people. :-)

I don't know much about pytest.  I started using Green before I discovered that pytest existed.  Can you be more specific about which "test discovery mechanisms" you are interested in Green supporting?

**Comment by MinchinWeb** [comment]
I've only looked at pytest is passing, but does support plugins. Presumably, green could be extended or rewritten as a pytest plugin. This way pytest could do the test discover and running, and the plugin version of green could reformat the pytest output so we get the nice green, red, etc dots.

There is a [pytest plugin](https://pypi.python.org/pypi/pytest-greendots) that sort of does this, but it hasn't been updated in 3 years and relies on `blessings`, which in turn relies on curses, which means it doesn't work on Windows.

**Comment by CleanCut** [comment]
Yep, someone could do that.  In fact, I probably would have tried it if I had known about pytest at the time of the events in the [origin story](https://github.com/CleanCut/green#origin-story).

I certainly don't have any interest in doing that now, though.  If someone loves green's output and pytest's behavior so much, they're welcome to make a green-like output plugin for pytest.  Nothing wrong with that!

I still want to know what Chris is actually asking for, though.  Can't really answer the question as it is.

**Comment by CleanCut** [comment]
Closing due to lack of response.
