### ISSUE TITLE
Which versions of Django are supported?

### ISSUE THREAD

**Issue by LaurensBosscher** [CleanCut/green#155]
Hi!

I tried running a Python 3.3/Django 1.8 project with the green testrunner and it just stalls no matter if I run 1 single test or all the tests in the project, if I place a few print statements in the green code I can see that the pool and targets do get created in runner.py:run but after that I never get a result. 

Could this be because Django before 1.9 do not support parallelisation of tests?

Edit: I see that Python 3.3 is not included in the Travis file either, might be worth supporting until September (when it's officially EOL) since CentOS is still on 3.3 for the time being or if there's a known reason why 3.3 would not work it might be worth mentioning in the readme.

**Comment by CleanCut** [comment]
[Green does not support Python 3.3](https://github.com/CleanCut/green#features)

I tried to in the start, but 3.3 was just a mess.  In my opinion Red Hat made a lousy decision shipping 3.3 instead of 3.4 which was already out when they released RHEL 7.0.  I use CentOS 7.x myself, and it's annoying that I *still* can't use a system-provided Python 3.

So, I hear you, but Green is probably never going to support Python 3.3.

**Comment by LaurensBosscher** [comment]
That's very understandable, I've upgraded my test environment tot 3.4 and unfortunately I still ran into the same problem described above even when I limit the test target to a single test.

I'll try to see if I can narrow down the case of this problem a bit more. Our project isn't that exotic but it's large enough that I suspect that a dependency other than Django could cause problems.

**Comment by CleanCut** [comment]
That's definitely a bug, then.  Have you tried making a green config file with `processes = 0`?  If you can trim it down to an example project, I could definitely take a look.
