### ISSUE TITLE
Raising an exception in setUpClass results in the test case being skipped

### ISSUE THREAD

**Issue by grant-zietsman** [CleanCut/green#244]
I would expect the exception to ripple up but it seems like it is swallowed and the tests in the failing test case are ignored. The result is a faulty positive.

**Comment by CleanCut** [comment]
(sigh) Ah, yes upstream `setUpClass` behavior is a travesty which I have [long](https://github.com/CleanCut/green/issues/159) [been](https://github.com/CleanCut/green/commit/9eba9ac2a3959318f68544f62302d944463e1363) [dealing](https://github.com/CleanCut/green/discussions/215) [with](https://github.com/CleanCut/green/commit/9f393edcaacc838bf3635f84a83537a6c7ce045b).

I'd welcome help finding and fixing the problem. It will most likely be in [one of these functions](https://github.com/CleanCut/green/blob/6b63dd3dd775ad908ea83add3a669185c4f21e7c/green/suite.py#L87-L169).  If you are on Python 3.7 or earlier, you'll want to focus on `_handleClassSetUpPre38`, otherwise look at `_handleClassSetUpPost38`.

Otherwise, post your output of `green --version` and your OS version and I'll see if I can get to it sometime.

**Comment by grant-zietsman** [comment]
I followed up and realised this was a calling code mistake. Apologies.

**Comment by CleanCut** [comment]
No worries! It's nice that there's not a larger issue to be tracked down this time. 😄
