### ISSUE TITLE
Re-run tests on file save?

### ISSUE THREAD

**Issue by vck3000** [CleanCut/green#246]
Hey guys,

Loving this library! 

Coming from NodeJS's Jest testing framework, a feature I've sorely missed is auto-rerunning the tests on file save. I couldn't find any information in green's README, so I was wondering if this had been considered before. From what I've seen, I haven't found a Python testing framework that supports this feature! 

I could try to write up a PR for it if this feature is approved :). 

Edit: Currently I'm using `entr` to mimic this behaviour. I use `find -name "*.py" | entr -c green -vv`.

**Comment by CleanCut** [comment]
Hi, thanks for you kind words!

I am not planning on implementing a feature like this since, as you demonstrated, it's pretty straight forward to do externally. If you would like to write up a PR, I'd be happy to review it and accept it if it's straightforward. Note that it would have to work on macOS, Linux, and Windows.

**Comment by CleanCut** [comment]
I'm going to go ahead and close this issue in favor of continuing the conversation on your PR #249

**Comment by vck3000** [comment]
Yeap, sorry. This has been on my mind and I have been wanting to do it. I'll get to this soon! Thank you.

**Comment by CleanCut** [comment]
No worries, there's no rush. 😄
